name: show project workflow
on:
  schedule: # Run workflow automatically
    - cron: "0 0 * * *" # 每天午夜运行一次
  workflow_dispatch: # Run workflow manually (without waiting for the cron to be called), through the GitHub Actions Workflow page directly
permissions:
  contents: write # To write the generated contents to the readme

jobs:
  update-main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: liyown/show-projects-action@v0.0.4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          owner: liyown